### ISSUE TITLE
Distorted Image

### ISSUE THREAD

**Issue by trvlr737** [ArduCAM/Arduino#111]
I am new to the ESP8266/ADRUCAM so, I apologize in advance. 
The problem I'm having occurs when I change the size of the image. The image is perfect at a resolution of 160x120. When I try a different resolution, the image doesn't capture/transfer properly. Please, any idea's would be a great help.

![160x120](https://cloud.githubusercontent.com/assets/19438616/20745905/5b2b219e-b6b1-11e6-92c6-6c540eaecfa9.jpg)
160x120

![640x480](https://cloud.githubusercontent.com/assets/19438616/20745948/87d17ba8-b6b1-11e6-9788-78ea8e2d3e0f.jpg)
640x480

**Comment by trvlr737** [comment]
Sorry. I should have added a little more info. 
This is the sketch. I haven't modified it in anyway.

https://github.com/ArduCAM/Arduino/blob/master/ArduCAM/examples/ESP8266/ArduCAM_ESP8266_OV2640_Capture/ArduCAM_ESP8266_OV2640_Capture.ino

Hardware: I'm using a LoLin NodeMcu V3 ESP8266 module and a ArduCam Mini 2MP.

**Comment by ArduCAM** [comment]
@trvlr737, It is the know issue. The ESP8266 library should be modified to work with our camera. Please use our ESP8266 library package.
http://www.arducam.com/downloads/ESP8266_UNO/ArduCAM_ESP8266_UNO_DS.pdf 
http://www.arducam.com/arducam-esp8266-uno-board-arduino-camera/

**Comment by trvlr737** [comment]
THANK YOU!! Works perfect!!

**Comment by NVergunst** [comment]
What is the actual problem that is solved by the modified library? I am not using an Arduino at all, but my picture comes out like yours. I'd really appreciate knowing which magic software settings need to be changed at the I2C/SPI level to get working data...
