### ISSUE TITLE
Arducam V2 FIFO Speed and Options

### ISSUE THREAD

**Issue by vuiseng9** [ArduCAM/Arduino#121]
Hi there, there are information about fifo in the FAQ in your webpage. we have a couple of follow up questions. We see a Winbond chip on the board, is that the FIFO? or is it part of the Altera chip?

What is the speed of transfer of a byte from FIFO to the microcontroller?  

As we notice a slow speed of reading the fifo, we are looking for options, just a conceptual discussion,
1. by replacing faster FIFO??
2. Skip the fifo, Storing the frame to flash (assuming 320x240 rgb55) which takes about 150KB? is this possible, i guess with current hardware setup, it's not possible.

Appreciate your attention :)

**Comment by supprot** [comment]
@vuiseng9 
Hi,
The speed of transfer is mainly depend on the SPI speed instead of the FIFO.
It's possible to skip the fifo if you have the camera interface in your board.

Regards,

ArduCAM support team
