### ISSUE TITLE
SD Card Initialization failure with ArduCAM Adapter Board

### ISSUE THREAD

**Issue by UMecamat** [ArduCAM/Arduino#149]
Hi all, 
This is my set up:
Arduino Mega and ArduCAM 4 Cameras Adapter Board to run two ArduCAM Mini rev B. 
Independently from the Adapter Board I use (I got 2), from the ArduCAM Mini I use (I tried with both 2 and 5MP cameras), from the microSD card (I tried with 4-5 different microSDs), I always get the same "SD Card Error" that concerns the failure of SD card initialisation. This failure happens always, independently of the example sketch I am using (even with former ArduCAM examples no longer in the github repo).
I noticed that without SDcard mounted the Adapter Board led blink properly, whilst with SDcard inserted, the led light is very (very very) low. Does anyone experienced the same very frustrating error?
Thanks

**Comment by jwerbs1217** [comment]
Having same issue

**Comment by supprot** [comment]
@UMecamat @jwerbs1217 
Hi,
Don't worry,what's the phenomenon when using only one camera with our adapter board on Arduino Mega platform?
What's your SD CS is ? 
Can you try to format your SD card?
Let us know if you need more help.
Regards,
ArduCAM support team.

**Comment by UMecamat** [comment]
Hi, 
- The adapter board is inserted directly to the Arduino Mega, and the SD_CS is 9, as for your examples;
- Tried with example "ArduCam_Mini_Capture2SD", one ArduCAM Mini rev B 5MP, and it works attached to CS4 (SPI_CS = 7); however, a new, very frustrating proble occurs, as the saved images are all and always 320x240, despite changing resolution in code (and I tried each possible resolution given in OV5642.h file)!!

- Also tried example "ArduCam_Mini_4CAM_Capture2SD" example with 2 ArduCAM Mini rev B 5MP. Result is again "SD card error". In the code, I excluded CAM3 and CAM4 as follows: 

`#include <Wire.h>
#include <ArduCAM.h>
#include <SPI.h>
#include <SD.h>
#include "memorysaver.h"
//This demo can only work on OV2640_MINI_2MP and  OV5642_MINI_5MP and OV5642_MINI_5MP_BIT_ROTATION_FIXED platform.
#if !(defined OV5642_MINI_5MP || defined OV5642_MINI_5MP_BIT_ROTATION_FIXED || defined OV2640_MINI_2MP)
#error Please select the hardware platform and camera module in the ../libraries/ArduCAM/memorysaver.h file
#endif

#define SD_CS 9

// Set pin 4,5,6,7 as the slave select for SPI:
const int CS1 = 4;
const int CS2 = 5;
//const int CS3 = 6;
//const int CS4 = 7;

bool CAM1_EXIST = false; 
bool CAM2_EXIST = false;
//bool CAM3_EXIST = false;
//bool CAM4_EXIST = false;


#if defined (OV2640_MINI_2MP)
ArduCAM myCAM1(OV2640, CS1);
ArduCAM myCAM2(OV2640, CS2);
//ArduCAM myCAM3(OV2640, CS3);
//ArduCAM myCAM4(OV2640, CS4);
#else
ArduCAM myCAM1(OV5642, CS1);
ArduCAM myCAM2(OV5642, CS2);
//ArduCAM myCAM3(OV5642, CS3);
//ArduCAM myCAM4(OV5642, CS4);
#endif

void setup() {
  // put your setup code here, to run once:
  uint8_t vid, pid;
  uint8_t temp;
  Wire.begin(); 
 Serial.begin(115200);
 Serial.println(F("ArduCAM Start!")); 
// set the CS output:
pinMode(CS1, OUTPUT);
pinMode(CS2, OUTPUT);
//pinMode(CS3, OUTPUT);
//pinMode(CS4, OUTPUT);
pinMode(SD_CS, OUTPUT);
// initialize SPI:
SPI.begin(); 
  //Check if the 4 ArduCAM Mini 2MP Cameras' SPI bus is OK
  while(1){
  myCAM1.write_reg(ARDUCHIP_TEST1, 0x55);
  temp = myCAM1.read_reg(ARDUCHIP_TEST1);
  if(temp != 0x55)
  {
    Serial.println(F("SPI1 interface Error!"));
  }else{
      CAM1_EXIST = true;
      Serial.println(F("SPI1 interface OK."));
    }
  myCAM2.write_reg(ARDUCHIP_TEST1, 0x55);
  temp = myCAM2.read_reg(ARDUCHIP_TEST1);
  if(temp != 0x55)
  {
    Serial.println("SPI2 interface Error!");
  }else{
      CAM2_EXIST = true;
      Serial.println(F("SPI2 interface OK."));
    }
  /*myCAM3.write_reg(ARDUCHIP_TEST1, 0x55);
  temp = myCAM3.read_reg(ARDUCHIP_TEST1);
  if(temp != 0x55)
  {
    Serial.println(F("SPI3 interface Error!"));
  }else{
      CAM3_EXIST = true;
      Serial.println(F("SPI3 interface OK."));
    }
  myCAM4.write_reg(ARDUCHIP_TEST1, 0x55);
  temp = myCAM4.read_reg(ARDUCHIP_TEST1);
  if(temp != 0x55)
  {
    Serial.println(F("SPI4 interface Error!"));
  }else{
      CAM4_EXIST = true;
      Serial.println(F("SPI4 interface OK."));
    }*/
   /*if(!(CAM1_EXIST||CAM2_EXIST||CAM3_EXIST||CAM4_EXIST)){ */  // changed to exclude CAM3 and CAM4
  if(!(CAM1_EXIST||CAM2_EXIST)){
      delay(1000);continue;    
      }
    else
    break;
  }
  //Initialize SD Card
  while(!SD.begin(SD_CS)){
    Serial.println(F("SD Card Error"));delay(1000);
  }
  Serial.println(F("SD Card detected."));
    
  #if defined (OV2640_MINI_2MP)
  while(1){
      //Check if the camera module type is OV2640
     myCAM1.wrSensorReg8_8(0xff, 0x01);
     myCAM1.rdSensorReg8_8(OV2640_CHIPID_HIGH, &vid);
     myCAM1.rdSensorReg8_8(OV2640_CHIPID_LOW, &pid);
     if ((vid != 0x26 ) && (( pid != 0x41 ) || ( pid != 0x42 ))){
      Serial.println(F("Can't find OV2640 module!"));
      delay(1000);continue;
      }else{
         Serial.println(F("OV2640 detected."));break;
        }
    } 
  #else
  while(1){
   //Check if the camera module type is OV5642
    myCAM1.wrSensorReg16_8(0xff, 0x01);
    myCAM1.rdSensorReg16_8(OV5642_CHIPID_HIGH, &vid);
    myCAM1.rdSensorReg16_8(OV5642_CHIPID_LOW, &pid);
     if((vid != 0x56) || (pid != 0x42)){
       Serial.println(F("Can't find OV5642 module!"));
       delay(1000);continue;
      }else{
        Serial.println(F("OV5642 detected."));break;
     }   
  }
   #endif
    myCAM1.set_format(JPEG);
    myCAM1.InitCAM();
  #if defined (OV2640_MINI_2MP)
    myCAM1.OV2640_set_JPEG_size(OV2640_320x240);
  #else
    myCAM1.write_reg(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);   //VSYNC is active HIGH
    myCAM2.write_reg(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);   //VSYNC is active HIGH
    //myCAM3.write_reg(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);   //VSYNC is active HIGH
    //myCAM4.write_reg(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);   //VSYNC is active HIGH
    myCAM1.OV5642_set_JPEG_size(OV5642_320x240);
 #endif
  delay(1000);
  myCAM1.clear_fifo_flag();
  myCAM2.clear_fifo_flag();
  //myCAM3.clear_fifo_flag();
  //myCAM4.clear_fifo_flag();
}
void loop() {
  if(CAM1_EXIST)
    myCAMSaveToSDFile(myCAM1);
    if(CAM2_EXIST)
    myCAMSaveToSDFile(myCAM2);
    //if(CAM3_EXIST)
    //myCAMSaveToSDFile(myCAM3);
    //if(CAM4_EXIST)
    //myCAMSaveToSDFile(myCAM4);
    delay(5000);
  }
void myCAMSaveToSDFile(ArduCAM myCAM){
  char str[8];
  byte buf[256];
  static int i = 0;
  static int k = 0;
  uint8_t temp = 0,temp_last=0;
  uint32_t length = 0;
  bool is_header = false;
  File outFile;
  //Flush the FIFO
  myCAM.flush_fifo();
  //Clear the capture done flag
  myCAM.clear_fifo_flag();
  //Start capture
  myCAM.start_capture();
  Serial.println("start Capture");
 while(!myCAM.get_bit(ARDUCHIP_TRIG , CAP_DONE_MASK));
 Serial.println(F("Capture Done."));  
 length = myCAM.read_fifo_length();
 Serial.print(F("The fifo length is :"));
 Serial.println(length, DEC);
  if (length >= MAX_FIFO_SIZE) //384K
  {
    Serial.println(F("Over size."));
    return ;
  }
    if (length == 0 ) //0 kb
  {
    Serial.println(F("Size is 0."));
    return ;
  }
 //Construct a file name
 k = k + 1;
 itoa(k, str, 10);
 strcat(str, ".jpg");
 //Open the new file
 outFile = SD.open(str, O_WRITE | O_CREAT | O_TRUNC);
 if(!outFile){
  Serial.println(F("File open faild"));
  return;
 }
myCAM.CS_LOW();
 myCAM.set_fifo_burst();
while ( length-- )
  {
    temp_last = temp;
    temp =  SPI.transfer(0x00);
    //Read JPEG data from FIFO
    if ( (temp == 0xD9) && (temp_last == 0xFF) ) //If find the end ,break while,
    {
        buf[i++] = temp;  //save the last  0XD9     
       //Write the remain bytes in the buffer
        myCAM.CS_HIGH();
        outFile.write(buf, i);    
      //Close the file
        outFile.close();
        Serial.println(F("Image save OK."));
        is_header = false;
        i = 0;
    }  
    if (is_header == true)
    { 
       //Write image data to buffer if not full
        if (i < 256)
        buf[i++] = temp;
        else
        {
          //Write 256 bytes image data to file
          myCAM.CS_HIGH();
          outFile.write(buf, 256);
          i = 0;
          buf[i++] = temp;
          myCAM.CS_LOW();
          myCAM.set_fifo_burst();
        }        
    }
    else if ((temp == 0xD8) & (temp_last == 0xFF))
    {
      is_header = true;
      buf[i++] = temp_last;
      buf[i++] = temp;   
    } 
  } 
}`

The same result if I use your original example without excluding CAM3 and CAM4 (which is obviously giving me a SPI3 and 4 error, but SPI1 and 2 are OK. 

This are, again, a very frustrating obstacles. Hope you will give some support without waiting so much time (25 days...)
All the best

**Comment by supprot** [comment]
@UMecamat 
Hi,we wil test it Next Mondayand give you a reply.
Regards,

**Comment by jwerbs1217** [comment]
So I opened the serial monitor and it looks like it's not getting past SD
card initialization. How do I set up my SD card? I've never done a project
with one? But more importantly for me, is there a way to have it send
information somewhere without an SD card first? For example, I'm trying to
send the photo through an XBEE to a remote controller. How might I go about
that? Thanks

**Comment by UMecamat** [comment]
@jwerbs1217 
Hi, perhaps we can help each other waiting for some support from ArduCam guys. 
As far as I understand, and assuming your are using one of the sketches provided by ArduCam and the adapter board, the SD card is initialised by the 'SD.begin(SD_CS)' command. This initialization can fails if one or more of the following occur: 
- wrong wiring (by default the SD pin is 9, as defined in '#define SD_CS 9'); if you are using the adapter board directly connected to Arduino UNO or Mega, this should be automatic; otherwise, if you are using cables, make make sure SD goes to 9;
- SD card fails because not properly formatted: this can occur especially if your pc is running on Linux distro (as is mine). I burnt 2 micro SD before to understand this...; and, as far as I know, each time you insert the SD card into the adapter board, new images from ArduCam overwrite the old ones...

As for the XBEE, I have not experience about it... but, I could suggest you to have a look to the ArduCam ESP8266 mcu which is perhaps the simplest way to send images... or try to use an ESP8266 coupled to your Arduino (I recently tried a Node MCU with a single ArduCam mini 5MP to send images to a server - both local and remote - and it worked fine, just google it; also tried Arduino UNO/Mega coupled with a very simple ESP8266-05 and ArduCam mini 5MP, which was also fine). The only drawback for all these options is that apparently you can use just one ArduCam mini 5MP; no way to use two cameras together, unless you find out how to double the ISP. Next days I will try to use an Arduino Uno or Mega with the ArduCam adapter borad and an ESP8266-05 module acting as WiFi station. If you are interested, I'll let you know. 
Hope this can help you 
Best

**Comment by supprot** [comment]
@UMecamat 
@jwerbs1217 
Hi,
We have tested the ArduCAM_MIni_4CAM_Capture2SD demo 
on MEGA 2560 board and it works fine.
We attach some picture for you.
Please check it again.
![07496e2e-3882-4816-8db5-7d6c1b2604d4](https://cloud.githubusercontent.com/assets/24818249/24384622/d04b8a2a-1397-11e7-95ec-147c3a3732b5.jpeg)
![a227259b-4e62-4e9c-ae84-bd92f79cc18c](https://cloud.githubusercontent.com/assets/24818249/24384627/d97221a4-1397-11e7-9a14-4dae04cf97ba.jpeg)

Let us know if you need more help.
Regards,
ArduCAM support team.

**Comment by UMecamat** [comment]
C'mon guys! One month waiting for some support and you send me such a ridiculous response? It really seems that you have not done any effort to check my previous message... Obviously the code pictured by you is the same I am using; obviously the Prints are different as when I use 2 cameras it does not work. Even more: as I said in ALL my messages, SD card error occur always and independently from the arduino (Uno or mega), from the SD card (I used a lot...), or adapter board (I have two). But all these issues were already explained in my previous comments. Do I should expect a real support from you? Any issue on SD cards perhaps not compatibles? Any problem with Linux users (I use Ubuntu)?

**Comment by ArduCAM** [comment]
@UMecamat
From your previous message, I'm not sure if the SD card worked or not.
> Tried with example "ArduCam_Mini_Capture2SD", one ArduCAM Mini rev B 5MP, and it works attached to CS4 (SPI_CS = 7); however, a new, very frustrating proble occurs, as the saved images are all and always 320x240, despite changing resolution in code (and I tried each possible resolution given in OV5642.h file)!!
If sd card works with ArduCam_Mini_Capture2SD, it should work with ArduCam_Mini_4CAM_Capture2SD example.
As you know the SD card is nothing to do with the camera, it should work alone even if no camera plugged.
Further more, you can use addtional sd card breakout board to your MEGA board without the 4camera adapter board.
Would you please show me some photos of your hardware setup?
Thanks.

**Comment by UMecamat** [comment]
Hi, thanks for reply
I have not the hardware with me right now, but the hardware set up is as follow, as already explained:
> The adapter board is inserted directly to the Arduino Mega, and the SD_CS is 9, as for your examples;
so... no wiring problems. 
I understand that is not a SD problem. However, the SD is initialised and run only when 1 ArduCam Mini is plugged into the 4 cameras adapter board. When I plug another camera, I always receive a SD failure message. Another problem occurs when running just one camera: even if setting a new resolution, the images saved on the SD card are only 320x240 resolution  (and obviously I do not know if this occurs also when more than one camera is plugged on the adapter board). Last, thank your for the advice on additional sd card breakout, but having bought 2 ArduCam adapter board I would like to us their sd card slots, not adding more hardware. 
Thanks in advance

**Comment by UMecamat** [comment]
sorry, wrong quoting in last message

**Comment by ArduCAM** [comment]
@UMecamat,
Our engineer will look into the resolution issue tomorrow, it must be a bug.
In terms of the SD card problem, make sure each of the camera works perfectly with sd card before plugging two cameras. More cameras means more load to the SPI bus, if one of the camera hold the bus, the SPI bus will be occupied.

**Comment by UMecamat** [comment]
Thanks, I'll check later if each cameras works with sd card before plugging 2 cameras, and wait for some fix about resolution problem.
Thanks

**Comment by supprot** [comment]
@UMecamat 
Hi,
We have tested it about resolution problem and it can work fine.
How do you change it's resolition? If you are using 5MP , you just
 change  myCAM1.OV5642_set_JPEG_size(OV5642_320x240) in the demo to get the
 resolution you want.

If your problem still exist, please check your memorysaver.h file to ensure
 you have enable OV5642_MINI_5MP and disable others . Then check the 
ArduCAM.cpp file and try replace the 
void ArduCAM::OV5642_set_JPEG_size(uint8_t size) funtion  with
void ArduCAM::OV5642_set_JPEG_size(uint8_t size)
{
#if defined(OV5642_CAM) || defined(OV5642_CAM_BIT_ROTATION_FIXED)|| defined(OV5642_MINI_5MP) || defined (OV5642_MINI_5MP_PLUS)
  uint8_t reg_val;

  switch (size)
  {
    case OV5642_320x240:
      wrSensorRegs16_8(ov5642_320x240);
      break;
    case OV5642_640x480:
      wrSensorRegs16_8(ov5642_640x480);
      break;
    case OV5642_1024x768:
      wrSensorRegs16_8(ov5642_1024x768);
      break;
    case OV5642_1280x960:
      wrSensorRegs16_8(ov5642_1280x960);
      break;
    case OV5642_1600x1200:
      wrSensorRegs16_8(ov5642_1600x1200);
      break;
    case OV5642_2048x1536:
      wrSensorRegs16_8(ov5642_2048x1536);
      break;
    case OV5642_2592x1944:
      wrSensorRegs16_8(ov5642_2592x1944);
      break;
    default:
      wrSensorRegs16_8(ov5642_320x240);
      break;
  }
#endif
}

![154424ae-c83e-4357-9745-7e1abba14888](https://cloud.githubusercontent.com/assets/24818249/24434280/301a8d56-1461-11e7-9525-1063f37894e6.jpeg)

Let us know if you need more help.
Regards,
ArduCAM support team.
