### ISSUE TITLE
OV5642 Write 50 frames to fifo. 

### ISSUE THREAD

**Issue by wdouglas1999** [ArduCAM/Arduino#168]
Hi. In the arducam examples they write 0x01 value into frame num for 2 frames and 0x07 to fill the buffer. My question is, how do I write for example 50 frames into the fifo buffer? Can anyone help?

**Comment by supprot** [comment]
@wdouglas1999 
Hi,
Our camera doesn't support writting for 50 frames.
If you write 0x07, it will capture until fill the buffer.
Let us know if you need more help.
Regards
ArduCAM support team.
