### ISSUE TITLE
How do I connect the OV5642 to an Arduino Mega?

### ISSUE THREAD

**Issue by jwerbs1217** [ArduCAM/Arduino#175]
Hi Arducam,

I have been testing out the OV5642 on my Arduino UNO and it has been working quite well. However, for my main project, I need to move it over to an Arduino MEGA , but when I switch to this Arduino it just gives me an SPI Interface Error. I am hooking it up to the exact same pins in the two arduinos but it is only working for the UNO. What should I do to fix this? I am using the LowPowerMode example for the arducam mini. 

Thanks!

**Comment by supprot** [comment]
@jwerbs1217 
Hi,

What's your SPI CS ?Please attach us some pictures about your phenomenon.

Let us know if you need more help.
Regards,
ArduCAM support team.

**Comment by jwerbs1217** [comment]
For anyone with this issue in the future, I figured it out. Connect MISO MOSI SCK to 50 51 52 respectively, CS to any digital pin (in the code this is designated as SPI_CS), VCC to 5V, GND to GND, and SDA and SCL to 20 and 21 respectively.

**Comment by supprot** [comment]
@jwerbs1217 
Hi,

Please connect the SPI signal from ISCP.
Please refer to the picture we attached to you.
![12](https://cloud.githubusercontent.com/assets/24818249/25118864/8c003032-244a-11e7-99a5-eaff19225612.png)
Let us know if you need more help.
Regards,
ArduCAM support team.
