### ISSUE TITLE
OV2640 mini 2MP connection to DUE

### ISSUE THREAD

**Issue by cblx5** [ArduCAM/Arduino#199]
Hi,

please confirm the connections of the OV2640 mini 2MP to a DUE.
I have seen some posts about it but not clearly explained and references
to made  ICSP when I think it was SPI header.

OV2640 -  DUE
==========
CS          -  10
MOS      -  MOSI  on SPI header
MISO     -  MISO on SPI header
SCK       -  SCK on SPI header
GND      - GND on SPI header
5V          -  5V   on SPI header !!!!!!!!   (this is the one of 3  not clear)
SDA        -  SDA1   (no pullup resistor  needed)
SCL         -  SCL1     (no pullup resistor  needed)

Thank you

**Comment by cblx5** [comment]
Hi,
Got my  OV2640 mini 2MP  working with DUE   and using an example.   If it helps anyone...

1) CS was pin 7 in code - so changed from 7 to 10 ( was building my own wiring cable before delivery of camera)
2) the "5V" on camera module is plugged into 3.3V on DUE
3) All others as above.

**Comment by i7-Ryzen** [comment]
Hi cblx5,

Is there a particular order for SPI? Thanks

**Comment by i7-Ryzen** [comment]
Solved. Thanks anyway :-)
