### ISSUE TITLE
SPI configuration for ArduCAM mini

### ISSUE THREAD

**Issue by rei-vilo** [ArduCAM/Arduino#2]
Whatever the example I try with the ArduCAM mini, same error message `SPI interface ERROR!`

What are the exact settings for SPI and especially, which mode?

Thank you!

**Comment by ArduCAM** [comment]
Have you resolved the SPI error? What's wrong with your setup?

**Comment by rei-vilo** [comment]
I'm trying to use the ArduCAM library on a LaunchPad MSP432. 

Problem is: SCK goes down after CS is down, resulting in a data mismatch.

![capture 2015-08-09 a 08 58 09](https://cloud.githubusercontent.com/assets/951776/9153866/f2a4a9c0-3e74-11e5-9bd2-4432efcb1a66.png)
