### ISSUE TITLE
(ArduCAM-Mini OV5642 & RaspberryPi) Empty JPEG

### ISSUE THREAD

**Issue by pavik1994** [ArduCAM/Arduino#201]
Hello.
I have ArduCAM-Mini OV5642 connect with RaspberryPi Compute Module by SPI and I2C. When I wrote
"sudo ./ov5642_capture -c test.jpg 320x240"
and i have:
"OV5642 detected.
Changed resolution to 320x240
Start Capture
CAM Capture Done
Reading FIFO and saving IMG
The length is 2584"
and in this moment program stop and my "test.jpg" is empty.
What can I do?

**Comment by hunterbryant** [comment]
Hey @pavik1994, I have been getting the same issue and was wondering if you solved it. I tried to debug the saving to SD card and noticed the code inside if statements to write to the sd were never called. Any help is appreciated

**Comment by martinlang83** [comment]
@hunterbryant same issue here. could you fix it?

**Comment by hunterbryant** [comment]
@martinlang83 👎

**Comment by UCTRONICS** [comment]
@hunterbryant @martinlang83 
Arducam has updated new Spi camera library for Raspberry Pi.
Please refer to the new library from https://github.com/ArduCAM/RaspberryPi/tree/master/SPI_Camera
