### ISSUE TITLE
OV5642 SPI interface error

### ISSUE THREAD

**Issue by e-coucou** [ArduCAM/Arduino#232]
Hi,
I received an OV5642 cam, connect to Photon. I check connection and code (SPI ok, CS pin ok ...) but I always receive "SPI interface error with code 255"
Is there an issue with the cam ? no led ? How can I check if the cam is ok ?
Thanks
Eric

**Comment by UCTRONICS** [comment]
@e-coucou 
Hi,
Do you use Mini 5MP plus camera ?
If so,the spi error has nothing to do with the camera. 
We suggest you check the spi interface firstly.

Let us know if you need more help.
Regards,
ArduCAM support team.

**Comment by e-coucou** [comment]
Thanks for your support.
Yes it's a Mini 5MP Plus Camera. I check the spi interface of the Photon (Particle) with a TFT ST3775 and it works !
I wonder if my cam is alive ? and how to check ?
Regards,
Eric

**Comment by e-coucou** [comment]
There is only a wiring issue !!!
