### ISSUE TITLE
Broken and shifted images

### ISSUE THREAD

**Issue by goetzmoritz** [ArduCAM/Arduino#238]
Sometimes it may happen that an image that is taken by the arducam mini 5MP with OV5640 that the actual image is shifted and or color-corrupted. The code I use is from the examples-library for image-capturing. I only altered the wifi-credentials. I use a lab-power-source of very high quality.
Is there any way to avoid that?

![37](https://user-images.githubusercontent.com/4437014/28317616-0803614e-6bc8-11e7-8719-404b11fb0f18.jpg)
Or sometimes like that:
![40](https://user-images.githubusercontent.com/4437014/28317710-6108e7aa-6bc8-11e7-9fd6-8330576b8bfc.jpg)

**Comment by supprot** [comment]
@goetzmoritz 
Hi,

Please send us the code your are using and we will check it for you.

Let us know if you need more help.
Regards,
ARduCAM support team.

**Comment by goetzmoritz** [comment]
I use the basic code that's provided in the samples. But anyways, I think key to this issue is a highly stable power source.
