### ISSUE TITLE
TFT not displaying images

### ISSUE THREAD

**Issue by mjs513** [ArduCAM/Arduino#248]
I purchased a Arducam LF Shield V2 + Camera Module + 3.2 Inch LCD for Arduino UNO Mega2560 DUE from amazon and am using it with a teensy 3.5.  I applied the mods for the teensy per the pull request and am working through the examples.  I got it to stream to the pc and save images to the sd card.  However, I can not get anything to display on lcd using any of the examples.

The current model of the lcd identified in the utft_spi.cpp file is the ssd1289, and was wondering if this is the correct TFT model?  I can not find anything on it on any of the webpages.

**Comment by UCTRONICS** [comment]
@mjs513
Hi,
Please use this demo from
https://github.com/ArduCAM/Arduino/tree/master/ArduCAM/examples/Shield_V2
Regards.
