### ISSUE TITLE
Shutter Speed

### ISSUE THREAD

**Issue by aph3xtwin** [ArduCAM/Arduino#26]
Hey there,

not quite an issue, but how can I manually adjust ISO, WB and Shutter Speed with OV2640 ArcuCam Mini?

Thanks!

**Comment by ArduCAM** [comment]
@goetz, You can find ISO WB, shutter related registers from the OV2640 datasheet. First you have to disable AGC, AWB, AEC to manually set these value. The ISO is controlled by the register 0x00 (GAIN) in the BANK1. The shutter is controlled by the exposure registers 0x45, 0x10, 0x04 of the bank1.
We can discuss more,so please send email to admin@arducam.com
