### ISSUE TITLE
i2c-address

### ISSUE THREAD

**Issue by goetzmoritz** [ArduCAM/Arduino#267]
Hi,

by unlucky coincidence the i2c-address of the arducam mini 5mp ov5640 is at 0x3c. I'd like to use another i2c-device having the same address. Is there any way to change the address?

thanks

**Comment by supprot** [comment]
@goetzmoritz
Hi,
The I2C address of the camera can not be changed.
Regards.

**Comment by goetzmoritz** [comment]
OK, thx
