### ISSUE TITLE
ArduCAM_Mini_OV2640_Yun_WebServer — IP Address Bug 

### ISSUE THREAD

**Issue by rei-vilo** [ArduCAM/Arduino#3]
There a bug affecting the IP address in the ** ArduCAM_Mini_OV2640_Yun_WebServer** example. 

By default, the last character is `#0A`, which makes the picture in the web page blank.

Just add `if (ip[m] == 0x0A) ip[m] = 0x00;` to line *ca.* 130

```
  while (q.available())
  {
    ip[m] = q.read();
    if (ip[m] == 0x0A) ip[m] = 0x00;
    m += 1;
  }
```

With this fix, the image is displayed correctly.

**Comment by ArduCAM** [comment]
Thanks for your comment. I do not have such problem with IP address parse.

![snap1](https://cloud.githubusercontent.com/assets/11016968/9153321/b6d150c6-3e81-11e5-9b45-e141c61d7cad.jpg)
![snap2](https://cloud.githubusercontent.com/assets/11016968/9153322/bdcc3652-3e81-11e5-8dad-8213672d6e03.jpg)

**Comment by rei-vilo** [comment]
My configuration includes

* Arduino Yun with YunSys v1.5.3
* Arduino IDE 1.6.5

What's yours?

**Comment by ArduCAM** [comment]
Firmware Version	OpenWRTYun Attitude Adjustment 1 / LuCI 0.11 Branch (0.11+svn10537)
Kernel Version	3.3.8
Arduino IDE 1.5.8
