### ISSUE TITLE
Camera (OV2640) slows ESP32 WiFi transfer considerably

### ISSUE THREAD

**Issue by Lakoja** [ArduCAM/Arduino#301]
Hi.
I have an odd problem I have been tracking now for 6 days and found out today that the Arducam plays at least a part in it:

I have an OV2640 Arducam and an ESP32. The latter one transfers the images over WiFi to a browser or controller.

If I connect the Arducam directly to my board and thus the camera is only an inch away from the ESP32 the WiFi transfer of that drops considerably. Especially there is now from time to time a data block that takes seconds to finish transfer.

I tried different ESPs analyzed power supply and fidgeted much with my code. But this problem also appears with simple test code and the camera simply being connected (not initialized).

The problem is however much weaker / nearly gone if I do **not** connect the camera directly to the board but use a 20cm cable instead.
See the two example images below.
This seems to be a problem of the wire lengths though because moving the camera next to the ESP32 while the cable is used doesn't cause any problems.

Does this ring any bells? Because I have no real idea at the moment.

![wagen_camera_nah](https://user-images.githubusercontent.com/1618905/36632285-47839062-1985-11e8-906d-6cdb30628386.JPG)
![wagen_camera_fern](https://user-images.githubusercontent.com/1618905/36632286-47a23c92-1985-11e8-9b84-862eb7a43f1e.JPG)

**Comment by supprot** [comment]
@Lakoja
Hi,
As normal , you'd better connect the Arducam directly to your board,which will get better signal of the image.
But if you connect the arducam with a cable, it maybe influence the signal of SPI transfer but not influence 
the signal of WIFI.

**Comment by Lakoja** [comment]
It seems to be indeed an interference problem while the ArduCam is capturing.

A small strategically placed piece of aluminum foil improves the situation dramatically.

![wagen_camera_alu](https://user-images.githubusercontent.com/1618905/36643397-e40fb7b0-1a4a-11e8-81e4-7aa6af5a84df.JPG)

**Comment by Lakoja** [comment]
Ok, that was spoken too soon.
I now need to use a bigger shielding and I have serialized camera action with Wifi transfer: Only one of them is active at a certain time.
If I omit either one of them I still have an extremely erratic Wifi connection.

**Comment by supprot** [comment]
@Lakoja
It's weird, it might have a lot to do with your floor.Our ArduCAM ESP32 UNO board is no such phenomenon.

**Comment by Lakoja** [comment]
I wondered about the common ground, too.
But moving the camera away by 2cm (with a long pin header) and 1cm out of the board area does not help unfortunately.

**Comment by Lakoja** [comment]
My observation was probably/mostly faulty:

I now "resolved" the problem by
- moving WiFi transfer code to the main thread
- Using WiFi channel 1 (instead of 8)

Couldn't really see any influence of the camera after that.

(Before that there was however a close correlation...)
