### ISSUE TITLE
OV7670: crop a captured image

### ISSUE THREAD

**Issue by marcogovo** [ArduCAM/Arduino#303]
Dear All, 

With ArduCAM libray, can i crop the captured image keeping only a small portion of it?
Or i have to do it 'manually' adding other code to my arduino sketch?

Thanks a lot,
Regards

**Comment by UCTRONICS** [comment]
@marcogovo 
Hi,
You should change the value of 'i 'and 'j' in the below codes:
//Read 320x240x2 byte from FIFO
//Save as RGB565 bmp format
for (i = 0; i < 240; i++)
for (j = 0; j < 320; j++)
{
  VH = myCAM.read_fifo();
  VL = myCAM.read_fifo();
  buf[k++] = VL;
  buf[k++] = VH;
  #if defined(ESP8266)
    yield();
  #endif
  //Write image data to bufer if not full
  if (k >= 256)
  {
    //Write 256 bytes image data to file from buffer
    outFile.write(buf, 256);
    k = 0;
  }
}

Let us know if you need more help.
Lvbin from UCTRONICS support team.
