### ISSUE TITLE
cannot capture image using ov2640 and arduino uno

### ISSUE THREAD

**Issue by chewani** [ArduCAM/Arduino#347]
hi. i'm new to arduino.. i have ov2640 and arduino uno board. i have tried the examples of arducam_mini_2mp_ov2640_functions. and it seems work and successfully upload into the board.
the serial monitor display:
ACK CMD ArduCAM start! END
ACK CMD SPI interface OK. END
ACK CMD OV2640 detected. END

unfortunately, as i open arducam_host v2, it shows
COM is open!
ArduCAM single
no image display. i'm stuck here.. please help me ASAP
![img_5988](https://user-images.githubusercontent.com/41840353/43360193-a55c706e-92e3-11e8-80d9-d55587c03ea9.JPG)
![img_5989](https://user-images.githubusercontent.com/41840353/43360195-a9593bca-92e3-11e8-8b58-aa5d8c79c3c2.JPG)

**Comment by UCTRONICS** [comment]
Hi,
You should close the serial monitor and open the Host V2.
Then choose the right serial port and 921600 baud rate.
Then press OPEN and  you will see the content with
 'SPI interface OK' 
'OV2640 detected'
when you press Capture, you will see a picture.

**Comment by UCTRONICS** [comment]
Hi,
You should close the serial monitor and open the Host V2.
Then choose the right serial port and 921600 baud rate.
Then press OPEN and  you will see the content with
 'SPI interface OK' 
'OV2640 detected'
when you press Capture, you will see a picture.

**Comment by UCTRONICS** [comment]
Hi,
You should close the serial monitor and open the Host V2.
Then choose the right serial port and 921600 baud rate.
Then press OPEN and  you will see the content with
 'SPI interface OK' 
'OV2640 detected'
when you press Capture, you will see a picture.
