### ISSUE TITLE
OV2460 parallel mode 

### ISSUE THREAD

**Issue by RogerHartmann** [ArduCAM/Arduino#355]
Not fully clear to me if the OV2640 is supported in parallel mode, meaning no SPI but direct data lines. 

When I quickly check the source code I read it like only SPI is supported, but when I check http://www.arducam.com/camera-modules/2mp-ov2640/ it looks like the OV2640 module I bought without SPI interface. 

Thanks for hints if and how I can connect the OV2640 in non-SPI mode. 

Cheers, Roger

**Comment by UCTRONICS** [comment]
@RogerHartmann 
About the 2MP, we have two kinds of interface, SPI interface, and parallel interface.
For the parallel interface, you can't connect it to the UNO directly and you should use it 
with our Arducam Shield V2 board.
http://www.uctronics.com/arducam-lf-camera-module-shield-3-2-inch-lcd-for-arduino-uno-mega2560-due.html

For the SPI interface, you can connect it to the UNO with spi and i2c interfaces directly.
http://www.uctronics.com/arducam-mini-module-camera-shield-w-2-mp-ov2640-for-arduino-uno-mega2560-board.html

**Comment by RogerHartmann** [comment]
Thanks @UCTRONICS for the quick reply. Looks like I have the wrong module then.
