### ISSUE TITLE
Cannot find MISO or MOSI pins on camera module

### ISSUE THREAD

**Issue by ironfist96** [ArduCAM/Arduino#371]
I'm trying to connect the camera (OV2640) to the Arduino mega2560, and I cannot understand which  pin is to be connected and where. The camera module that I have looks a bit different from what the others have and as such, I wasn't able to find a post with a similar problem.
![whatsapp image 2018-10-22 at 8 26 02 pm](https://user-images.githubusercontent.com/16142786/47304882-f0b97a00-d638-11e8-9c94-3e944fa0e645.jpeg)

As you can see this module doesn't have a MISO, MOSI, and the other pins of the like, so can you please help me out with the pin configurations?

![whatsapp image 2018-10-22 at 8 34 14 pm](https://user-images.githubusercontent.com/16142786/47305271-febbca80-d639-11e8-9eb9-88bbcb45efb6.jpeg)

**Comment by UCTRONICS** [comment]
@ironfist96 
This kind of camera should be used with our Arducam shield V2 board.
If you want to use SPI camera, please refer to the https://www.amazon.com/Arducam-Module-Megapixels-Arduino-Mega2560/dp/B012UXNDOY/ref=sr_1_3?m=A2IAB2RW3LLT8D&s=merchant-items&ie=UTF8&qid=1540259687&sr=1-3&refinements=p_4%3AArducam

**Comment by ironfist96** [comment]
@UCTRONICS
Thanks for the info, but is there any way I could use the this camera module without the arducam shield? Time is of the essence for my project and finding the shield and shipping it will take time.

**Comment by UCTRONICS** [comment]
@ironfist96 
There are no other ways to use this module on mega2560.
I advise you replace a camera.

**Comment by ironfist96** [comment]
@UCTRONICS Ah gotcha. I guess I'll be ordering an SPI Camera module. Thanks for the help.
