### ISSUE TITLE
Upload pictures taken to my server?

### ISSUE THREAD

**Issue by mnotgod96** [ArduCAM/Arduino#394]
Hi ArduCam team,

I am doing a project based on ESP-12E board and I want to upload pictures taken by OV2640 mini camera to my website server. However, I don't have too much experience in embedded system so I am wondering if you have any example that illustrates how to do that. Thank you for any potential help!

**Comment by ArduCAM** [comment]
You can use the library from https://github.com/ArduCAM/ArduCAM_ESP8266_UNO
