### ISSUE TITLE
Ov5642 5mp cam

### ISSUE THREAD

**Issue by jopa95** [ArduCAM/Arduino#410]
I use the ov5642 5MP  plus cam and your example from the site of the o5642 plus functions.
If I start your example every time stops on the same place, it never goes to “capture done”
I include all necessary libraries.
Someone help
Here is also a picture of serial monitor.
![C0B63917-A3AB-4B21-86B3-DA86907BD6E4](https://user-images.githubusercontent.com/48956017/56906750-2c7b4380-6aa3-11e9-834e-dfad28501e8a.jpeg)

**Comment by jopa95** [comment]
Help someone?

**Comment by UCTRONICS** [comment]
@jopa95 
Which demo you are using? Our Video Streaming demo should use the Host V2 application .

**Comment by jopa95** [comment]
It take sometimes a photo , but usually it stops by cam start single shot . I think the profram don’t get into the if myCamgetbit function , dont know why? Can someone help
