### ISSUE TITLE
How to send the image data to the computer without the given host app?

### ISSUE THREAD

**Issue by QijiaShao** [ArduCAM/Arduino#492]
Basically I want to find a way to send the image data to the computer without the given host app. Because I want to change the exposure time. It seems the changes cannot be recognized with the host app. Any suggestion? Thanks!

**Comment by ArducamSupport** [comment]
Hi,
We have replied to you on the forum.
[https://www.arducam.com/forums/topic/python-code-for-capturing-the-picture-with-2mp-plus/](https://www.arducam.com/forums/topic/python-code-for-capturing-the-picture-with-2mp-plus/)
