### ISSUE TITLE
Connecting OV2640 camera to Arduino BLE 33

### ISSUE THREAD

**Issue by gigwegbe** [ArduCAM/Arduino#496]
I recently got the [OV2640 camera]( https://alexnld.com/product/xd-95-ov2640-camera-module-200w-pixel-stm32f4-driver-support-jpeg-output-for-arduino/), and there is no documentation on how to connect it to Arduino BLE 33/Arduino Nano. I will need the wiring connection and any other useful link. Thanks

**Comment by ArducamSupport** [comment]
Hi,
The camera we use on arduino is spi interface, as shown below.
![image](https://user-images.githubusercontent.com/48546045/89962311-f0a7c580-dc76-11ea-8536-1f4ef3067004.png)

The camera you purchased is not our product, please contact the dealer where you purchased the product.

**Comment by ArducamSupport** [comment]
This is the product link of our spi camera：[https://www.arducam.com/docs/spi-cameras-for-arduino/](https://www.arducam.com/docs/spi-cameras-for-arduino/)
Hope it helps you.
