### ISSUE TITLE
How to get YUV422 output

### ISSUE THREAD

**Issue by esterer** [ArduCAM/Arduino#497]
"set_format" doesn't include YUV422. Can I just write to 0xDA and 0xC2?

**Comment by ArducamSupport** [comment]
Hi，
Do you mean the mipi 2mp plus camera?If it is, then it is definitely not enough to modify the above-mentioned registers only. The YUV format output requires multiple sets of registers to cooperate and adjust. You can refer to the YUV configuration in follow file to set it yourself.
[OV2640 Camera Module Software Application Notes1.04 OVT.pdf](https://github.com/ArduCAM/Arduino/files/5100052/OV2640.Camera.Module.Software.Application.Notes1.04.OVT.pdf)

**Comment by esterer** [comment]
thank you this is what I needed
