### ISSUE TITLE
Arducam DISPLAY GARBAGE WITH OV2640_MINI_2MP_PLUS WHEN CONNECTED TO MicroSD CARD ADAPTER

### ISSUE THREAD

**Issue by t1jani** [ArduCAM/Arduino#502]
I have wired up my Arducam OV2640_MINI_2MP_PLUS to an the MicroSD Card Adapter HW-125 which is connected an arduino uno. I am using default example from the library included and all I get is garbage data. Here is an image of my serial monitor

![Capture](https://user-images.githubusercontent.com/54343223/95694891-fa5b9400-0bf9-11eb-9de3-3d88d0ae8e75.PNG)

**Comment by ArducamSupport** [comment]
Hi，
Due to the poor design of some SD card slots, the SPI bus is not released, which cause the bus can't connect multi device. So I advise you change another SD card slot to test again.

**Comment by t1jani** [comment]
When you say SPI bus do you mean the pin slot on the Arduino
