### ISSUE TITLE
read_fifo_length() doesn't return an accurate value for small images

### ISSUE THREAD

**Issue by DasHammer** [ArduCAM/Arduino#52]
read_fifo_length() doesn't appear to return an accurate value for small image sizes. For example, when the resolution is set to OV2640_160x120 the size of the image reported by read_fifo_length() returns 1024 or 2048. However, the image data is actually much less than this value.

**Comment by ArduCAM** [comment]
@ DasHammer, Yes you are right, it is the nature of the OV2640 sensor, it pads additional dummy data after JPEG stream tail..

**Comment by br101** [comment]
This is still an issue, please reopen
