### ISSUE TITLE
Missing *.h files (Wire, SPI, HardwareSerial_

### ISSUE THREAD

**Issue by claymelugin** [ArduCAM/Arduino#57]
Hopefully this is an easy to fix issue.  When compiling ArduCAM.cpp for the first time I found that the following header files are not on GitHub.

Wire.h
SPI.h
HardwareSerial.h

But they are needed to compile.

Where can I get these files ?

-Clay

**Comment by ArduCAM** [comment]
@Clay, these header files are in the Arduino IDE where you download from the arduino.cc.
