### ISSUE TITLE
Source code for ArduCAM_host_v1.0.exe

### ISSUE THREAD

**Issue by kennsippell** [ArduCAM/Arduino#68]
Is the source code for ArduCAM_host_v1.0.exe available somewhere? Sorry if this is in your depot and I just can't locate it.

**Comment by lena94** [comment]
you can find it under (ArduCAM host application demonstration): 
http://www.arducam.com/arducam-host-application-demonstration/#more-813

**Comment by ArduCAM** [comment]
@Pajama, Please find the source code from www.arducam.com/downloads/app/ArduCAM_Mini_C_sharp_20150413.zip

**Comment by kennsippell** [comment]
Thanks!
