### ISSUE TITLE
ArduCAM_OV2640_Digital_Camera - Invalid JPG

### ISSUE THREAD

**Issue by huguesbr** [ArduCAM/Arduino#94]
I'm trying to run `ArduCAM_OV2640_Digital_Camera` exemple.

The video feedback loop work correctly (I can see the video on the LCD screen), but when I try to capture an image, the captured image seem to be in an invalid format. See attached JPG file.
![1](https://cloud.githubusercontent.com/assets/1517759/19148082/5bc067b6-8bbb-11e6-8705-1ee2da87b5de.JPG)

Hardware:
- Arduino Mega board 2560 - REV 03
- Arducam LCD Screen Shield w/ OV2640 omnivision module

Any idea?

**Comment by Shdwdrgn** [comment]
See issue #21, I had a similar problem until I changed bufferSize to 2048.

**Comment by huguesbr** [comment]
@Shdwdrgn it was due to a different serial port speed between Arduino App / Device :(

Thanks

**Comment by Shdwdrgn** [comment]
Ah, sounds easy enough, glad you got it figured out.

**Comment by huguesbr** [comment]
@Shdwdrgn a bit ashamed 😳...
