### ISSUE TITLE
Sketch is too big for Aurduino UNO

### ISSUE THREAD

**Issue by vitasam** [ArduCAM/Arduino#95]
Hello,
I'm trying to build \Arduino\OV7670FIFO\OV7670FIFO.ino sketch, but IDE complains about size:

```
Sketch uses 39,682 bytes (123%) of program storage space. Maximum is 32,256 bytes.
Global variables use 1,958 bytes (95%) of dynamic memory, leaving 90 bytes for local variables. Maximum is 2,048 bytes.
```

Should it suppose to work with Arduino UNO?

**Comment by ArduCAM** [comment]
@vitasam, you have to use Arduino Mega2560 to run the example. UNO has less memory and pins to run the OV7670 with FIFO module.
